apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: onixweb-argo-applivation
   namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/pvaranasi95/Jenkins-Sonarqube-Docker.git
    targetRevision: HEAD
    path: K8s
  destination:
      server: https://kubernetes.default.svc
      namespace: onixweb
  syncPolicy:
    syncOptions:
    -   CreateNamespace=true
    automated:
       selfHeal: true
       prune: true

      
